name: Webapp CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontned
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: false
      - name: Build and Push docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp-frontend:latest

  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: false
      - name: Build and Push docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp-backend:latest

  deploy-prod:
    name: Deploy to PROD (K8S)
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Deploy Frontend to PROD
        run: |
          kubectl set image deployment/frontend-deployment frontend=mtararujs/webapp-frontend:latest
          kubectl rollout restart deployment/frontend-deployment
      - name: Deploy Backend to PROD
        run: |
          kubectl set image deployment/backend-deployment backend=mtararujs/webapp-backend:latest
          kubectl rollout restart deployment/backend-deployment

  api-tests-prod:
    name: API tests on PROD
    runs-on: self-hosted
    needs: [deploy-prod]
    steps:
      - name: Test Step
        run: echo "Test step"

  rollback-backend:
    name: Backend rollback on PROD
    runs-on: self-hosted
    needs: [api-tests-prod]
    steps:
      - name: Test Step
        run: echo "Test step"

