name: Webapp CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontned
    runs-on: self-hosted
    steps:
      - name: Test Step
        run: echo "Test step"
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Test Step
        run: echo "Test step"
  deploy-prod:
    name: Deploy to PROD (K8S)
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Test Step
        run: echo "Test step"
  api-tests-prod:
    name: API tests on PROD
    runs-on: self-hosted
    needs: [deploy-prod]
    steps:
      - name: Test Step
        run: echo "Test step"
  rollback-backend:
    name: Backend rollback on PROD
    runs-on: self-hosted
    needs: [api-tests-prod]
    steps:
      - name: Test Step
        run: echo "Test step"

